### ISSUE TITLE
looping 

### ISSUE THREAD

**Issue by Lablnet** [homelancer/HomeTools#2]
i install helloworldsample add on i enter oh good yeah in message
when i save see what happen 
![screenshot 273](https://user-images.githubusercontent.com/27757785/28213528-4c303c86-685b-11e7-9016-7a3a68b1e695.png)
also you can not provide document how to write a simple add on add message button soon etc thanks

**Comment by homelancer** [comment]
This is the  sample add-on and this is normal for the Hello World add-on. It is supposed to show _annoying_ messages all over.

It signifies how many times the add-on is being called when browsing about the Ossn site.

**Comment by homelancer** [comment]
Added a checking if the message is already on the message array.

**Comment by Lablnet** [comment]
thanks
